// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFdCNdE7wijnZnDGvEls-Qs5_67av9ceQ',
    appId: '1:479016215439:web:a589e0a551009e337121fa',
    messagingSenderId: '479016215439',
    projectId: 'projectwork-79584',
    authDomain: 'projectwork-79584.firebaseapp.com',
    storageBucket: 'projectwork-79584.firebasestorage.app',
    measurementId: 'G-QQ4PTN6K1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGivWkEbA-fw6pggur-kvoLTx7kCxdztc',
    appId: '1:479016215439:android:5be5ce3f04389e757121fa',
    messagingSenderId: '479016215439',
    projectId: 'projectwork-79584',
    storageBucket: 'projectwork-79584.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSaWgfSRF8zdJ0TuPXQn9p0K_CYK0-COQ',
    appId: '1:479016215439:ios:804796005e2529727121fa',
    messagingSenderId: '479016215439',
    projectId: 'projectwork-79584',
    storageBucket: 'projectwork-79584.firebasestorage.app',
    iosBundleId: 'com.example.projectapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSaWgfSRF8zdJ0TuPXQn9p0K_CYK0-COQ',
    appId: '1:479016215439:ios:804796005e2529727121fa',
    messagingSenderId: '479016215439',
    projectId: 'projectwork-79584',
    storageBucket: 'projectwork-79584.firebasestorage.app',
    iosBundleId: 'com.example.projectapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFdCNdE7wijnZnDGvEls-Qs5_67av9ceQ',
    appId: '1:479016215439:web:8a44f4a19cb13d677121fa',
    messagingSenderId: '479016215439',
    projectId: 'projectwork-79584',
    authDomain: 'projectwork-79584.firebaseapp.com',
    storageBucket: 'projectwork-79584.firebasestorage.app',
    measurementId: 'G-HPNFRZVFS4',
  );
}
